spring:
  application:
    name: eataku

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

jpa:
  hibernate:
    ddl-auto: create
  show-sql: true
  database: mysql
  properties:
    hibernate:
      '[format_sql]': true

cloud:
  aws:
    credentials:
      access-key: ${aws.credentials.access-key}
      secret-key: ${aws.credentials.secret-key}
    stack:
      auto: false
    region:
      static: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: ${aws.s3.bucket}